/**
 * all answers is here
 */
exports.e1 = [{ "Tables_in_oreilly": "account" }, { "Tables_in_oreilly": "branch" }, { "Tables_in_oreilly": "business" }, { "Tables_in_oreilly": "customer" }, { "Tables_in_oreilly": "department" }, { "Tables_in_oreilly": "employee" }, { "Tables_in_oreilly": "individual" }, { "Tables_in_oreilly": "officer" }, { "Tables_in_oreilly": "product" }, { "Tables_in_oreilly": "product_type" }, { "Tables_in_oreilly": "transaction" }]

exports.c3p1 = [{ "emp_id": 2, "fname": "Susan", "lname": "Barker" }, { "emp_id": 13, "fname": "John", "lname": "Blake" }, { "emp_id": 6, "fname": "Helen", "lname": "Fleming" }, { "emp_id": 17, "fname": "Beth", "lname": "Fowler" }, { "emp_id": 5, "fname": "John", "lname": "Gooding" }, { "emp_id": 9, "fname": "Jane", "lname": "Grossman" }, { "emp_id": 4, "fname": "Susan", "lname": "Hawthorne" }, { "emp_id": 12, "fname": "Samantha", "lname": "Jameson" }, { "emp_id": 16, "fname": "Theresa", "lname": "Markham" }, { "emp_id": 14, "fname": "Cindy", "lname": "Mason" }, { "emp_id": 8, "fname": "Sarah", "lname": "Parker" }, { "emp_id": 15, "fname": "Frank", "lname": "Portman" }, { "emp_id": 10, "fname": "Paula", "lname": "Roberts" }, { "emp_id": 1, "fname": "Michael", "lname": "Smith" }, { "emp_id": 7, "fname": "Chris", "lname": "Tucker" }, { "emp_id": 18, "fname": "Rick", "lname": "Tulman" }, { "emp_id": 3, "fname": "Robert", "lname": "Tyler" }, { "emp_id": 11, "fname": "Thomas", "lname": "Ziegler" }]

exports.c3p2 = [{ "account_id": 3, "cust_id": 1, "avail_balance": 3000 }, { "account_id": 12, "cust_id": 4, "avail_balance": 5487.09 }, { "account_id": 15, "cust_id": 6, "avail_balance": 10000 }, { "account_id": 17, "cust_id": 7, "avail_balance": 5000 }, { "account_id": 18, "cust_id": 8, "avail_balance": 3487.19 }, { "account_id": 22, "cust_id": 9, "avail_balance": 9345.55 }, { "account_id": 24, "cust_id": 10, "avail_balance": 23575.12 }, { "account_id": 27, "cust_id": 11, "avail_balance": 9345.55 }, { "account_id": 28, "cust_id": 12, "avail_balance": 38552.05 }, { "account_id": 29, "cust_id": 13, "avail_balance": 50000 }]

exports.c3p3 = [{ "account_id": 1, "product_cd": "CHK", "cust_id": 1, "open_date": "2000-01-15T00:00:00.000Z", "close_date": null, "last_activity_date": "2005-01-04T00:00:00.000Z", "status": "ACTIVE", "open_branch_id": 2, "open_emp_id": 10, "avail_balance": 1057.75, "pending_balance": 1057.75 }, { "account_id": 2, "product_cd": "SAV", "cust_id": 1, "open_date": "2000-01-15T00:00:00.000Z", "close_date": null, "last_activity_date": "2004-12-19T00:00:00.000Z", "status": "ACTIVE", "open_branch_id": 2, "open_emp_id": 10, "avail_balance": 500, "pending_balance": 500 }, { "account_id": 3, "product_cd": "CD", "cust_id": 1, "open_date": "2004-06-30T00:00:00.000Z", "close_date": null, "last_activity_date": "2004-06-30T00:00:00.000Z", "status": "ACTIVE", "open_branch_id": 2, "open_emp_id": 10, "avail_balance": 3000, "pending_balance": 3000 }]