/**
 * all answers is here
 */
exports.e1 = [{ "Tables_in_oreilly": "account" }, { "Tables_in_oreilly": "branch" }, { "Tables_in_oreilly": "business" }, { "Tables_in_oreilly": "customer" }, { "Tables_in_oreilly": "department" }, { "Tables_in_oreilly": "employee" }, { "Tables_in_oreilly": "individual" }, { "Tables_in_oreilly": "officer" }, { "Tables_in_oreilly": "product" }, { "Tables_in_oreilly": "product_type" }, { "Tables_in_oreilly": "transaction" }]

exports.c3p1 = [{ "emp_id": 2, "fname": "Susan", "lname": "Barker" }, { "emp_id": 13, "fname": "John", "lname": "Blake" }, { "emp_id": 6, "fname": "Helen", "lname": "Fleming" }, { "emp_id": 17, "fname": "Beth", "lname": "Fowler" }, { "emp_id": 5, "fname": "John", "lname": "Gooding" }, { "emp_id": 9, "fname": "Jane", "lname": "Grossman" }, { "emp_id": 4, "fname": "Susan", "lname": "Hawthorne" }, { "emp_id": 12, "fname": "Samantha", "lname": "Jameson" }, { "emp_id": 16, "fname": "Theresa", "lname": "Markham" }, { "emp_id": 14, "fname": "Cindy", "lname": "Mason" }, { "emp_id": 8, "fname": "Sarah", "lname": "Parker" }, { "emp_id": 15, "fname": "Frank", "lname": "Portman" }, { "emp_id": 10, "fname": "Paula", "lname": "Roberts" }, { "emp_id": 1, "fname": "Michael", "lname": "Smith" }, { "emp_id": 7, "fname": "Chris", "lname": "Tucker" }, { "emp_id": 18, "fname": "Rick", "lname": "Tulman" }, { "emp_id": 3, "fname": "Robert", "lname": "Tyler" }, { "emp_id": 11, "fname": "Thomas", "lname": "Ziegler" }]

exports.c3p2 = [{ "account_id": 3, "cust_id": 1, "avail_balance": 3000 }, { "account_id": 12, "cust_id": 4, "avail_balance": 5487.09 }, { "account_id": 15, "cust_id": 6, "avail_balance": 10000 }, { "account_id": 17, "cust_id": 7, "avail_balance": 5000 }, { "account_id": 18, "cust_id": 8, "avail_balance": 3487.19 }, { "account_id": 22, "cust_id": 9, "avail_balance": 9345.55 }, { "account_id": 24, "cust_id": 10, "avail_balance": 23575.12 }, { "account_id": 27, "cust_id": 11, "avail_balance": 9345.55 }, { "account_id": 28, "cust_id": 12, "avail_balance": 38552.05 }, { "account_id": 29, "cust_id": 13, "avail_balance": 50000 }]

exports.c3p3 = [{ "open_emp_id": 1 }, { "open_emp_id": 10 }, { "open_emp_id": 13 }, { "open_emp_id": 16 }]

exports.c4p3 = [{ "account_id": 7, "open_date": "2002-11-23T00:00:00.000Z" }, { "account_id": 8, "open_date": "2002-12-15T00:00:00.000Z" }, { "account_id": 14, "open_date": "2002-08-24T00:00:00.000Z" }, { "account_id": 24, "open_date": "2002-09-30T00:00:00.000Z" }, { "account_id": 25, "open_date": "2002-10-01T00:00:00.000Z" }]

exports.c4p4 = [{ "cust_id": 1, "lname": "Hadley", "fname": "James" }, { "cust_id": 9, "lname": "Farley", "fname": "Richard" }]

exports.c5p2 = [{ "account_id": 1, "fed_id": "111-11-1111", "name": "checking account" }, { "account_id": 2, "fed_id": "111-11-1111", "name": "savings account" }, { "account_id": 3, "fed_id": "111-11-1111", "name": "certificate of deposit" }, { "account_id": 4, "fed_id": "222-22-2222", "name": "checking account" }, { "account_id": 5, "fed_id": "222-22-2222", "name": "savings account" }, { "account_id": 7, "fed_id": "333-33-3333", "name": "checking account" }, { "account_id": 8, "fed_id": "333-33-3333", "name": "money market account" }, { "account_id": 10, "fed_id": "444-44-4444", "name": "checking account" }, { "account_id": 11, "fed_id": "444-44-4444", "name": "savings account" }, { "account_id": 12, "fed_id": "444-44-4444", "name": "money market account" }, { "account_id": 13, "fed_id": "555-55-5555", "name": "checking account" }, { "account_id": 14, "fed_id": "666-66-6666", "name": "checking account" }, { "account_id": 15, "fed_id": "666-66-6666", "name": "certificate of deposit" }, { "account_id": 17, "fed_id": "777-77-7777", "name": "certificate of deposit" }, { "account_id": 18, "fed_id": "888-88-8888", "name": "checking account" }, { "account_id": 19, "fed_id": "888-88-8888", "name": "savings account" }, { "account_id": 21, "fed_id": "999-99-9999", "name": "checking account" }, { "account_id": 22, "fed_id": "999-99-9999", "name": "money market account" }, { "account_id": 23, "fed_id": "999-99-9999", "name": "certificate of deposit" }]

exports.c5p3 = [{ "emp_id": 4, "fname": "Susan", "lname": "Hawthorne" }, { "emp_id": 5, "fname": "John", "lname": "Gooding" }]

exports.c6p2 = [{ "fname": "James", "lname": "Hadley" }, { "fname": "Susan", "lname": "Tingley" }, { "fname": "Frank", "lname": "Tucker" }, { "fname": "John", "lname": "Hayward" }, { "fname": "Charles", "lname": "Frasier" }, { "fname": "John", "lname": "Spencer" }, { "fname": "Margaret", "lname": "Young" }, { "fname": "Louis", "lname": "Blake" }, { "fname": "Richard", "lname": "Farley" }, { "fname": "Michael", "lname": "Smith" }, { "fname": "Susan", "lname": "Barker" }, { "fname": "Robert", "lname": "Tyler" }, { "fname": "Susan", "lname": "Hawthorne" }, { "fname": "John", "lname": "Gooding" }, { "fname": "Helen", "lname": "Fleming" }, { "fname": "Chris", "lname": "Tucker" }, { "fname": "Sarah", "lname": "Parker" }, { "fname": "Jane", "lname": "Grossman" }, { "fname": "Paula", "lname": "Roberts" }, { "fname": "Thomas", "lname": "Ziegler" }, { "fname": "Samantha", "lname": "Jameson" }, { "fname": "John", "lname": "Blake" }, { "fname": "Cindy", "lname": "Mason" }, { "fname": "Frank", "lname": "Portman" }, { "fname": "Theresa", "lname": "Markham" }, { "fname": "Beth", "lname": "Fowler" }, { "fname": "Rick", "lname": "Tulman" }]

exports.c6p3 = [{ "fname": "Susan", "lname": "Barker" }, { "fname": "Louis", "lname": "Blake" }, { "fname": "John", "lname": "Blake" }, { "fname": "Richard", "lname": "Farley" }, { "fname": "Helen", "lname": "Fleming" }, { "fname": "Beth", "lname": "Fowler" }, { "fname": "Charles", "lname": "Frasier" }, { "fname": "John", "lname": "Gooding" }, { "fname": "Jane", "lname": "Grossman" }, { "fname": "James", "lname": "Hadley" }, { "fname": "Susan", "lname": "Hawthorne" }, { "fname": "John", "lname": "Hayward" }, { "fname": "Samantha", "lname": "Jameson" }, { "fname": "Theresa", "lname": "Markham" }, { "fname": "Cindy", "lname": "Mason" }, { "fname": "Sarah", "lname": "Parker" }, { "fname": "Frank", "lname": "Portman" }, { "fname": "Paula", "lname": "Roberts" }, { "fname": "Michael", "lname": "Smith" }, { "fname": "John", "lname": "Spencer" }, { "fname": "Susan", "lname": "Tingley" }, { "fname": "Frank", "lname": "Tucker" }, { "fname": "Chris", "lname": "Tucker" }, { "fname": "Rick", "lname": "Tulman" }, { "fname": "Robert", "lname": "Tyler" }, { "fname": "Margaret", "lname": "Young" }, { "fname": "Thomas", "lname": "Ziegler" }]

exports.c7p1 = [{ "SUBSTRING('Please find the substring in this string',17,9)": "substring" }]

exports.c7p2 = [{ "ABS(-25.76823)": 25.76823, "SIGN(-25.76823)": -1, "ROUND(-25.76823, 2)": -25.77 }]

exports.c8p1 = [{ "COUNT(*)": 24 }]

exports.c8p2 = [{ "cust_id": 1, "COUNT(*)": 3 }, { "cust_id": 2, "COUNT(*)": 2 }, { "cust_id": 3, "COUNT(*)": 2 }, { "cust_id": 4, "COUNT(*)": 3 }, { "cust_id": 5, "COUNT(*)": 1 }, { "cust_id": 6, "COUNT(*)": 2 }, { "cust_id": 7, "COUNT(*)": 1 }, { "cust_id": 8, "COUNT(*)": 2 }, { "cust_id": 9, "COUNT(*)": 3 }, { "cust_id": 10, "COUNT(*)": 2 }, { "cust_id": 11, "COUNT(*)": 1 }, { "cust_id": 12, "COUNT(*)": 1 }, { "cust_id": 13, "COUNT(*)": 1 }]

exports.c8p3 = [{ "cust_id": 1, "COUNT(*)": 3 }, { "cust_id": 2, "COUNT(*)": 2 }, { "cust_id": 3, "COUNT(*)": 2 }, { "cust_id": 4, "COUNT(*)": 3 }, { "cust_id": 6, "COUNT(*)": 2 }, { "cust_id": 8, "COUNT(*)": 2 }, { "cust_id": 9, "COUNT(*)": 3 }, { "cust_id": 10, "COUNT(*)": 2 }]

exports.c9p1 = [{ "account_id": 25, "product_cd": "BUS", "cust_id": 10, "avail_balance": 0 }, { "account_id": 27, "product_cd": "BUS", "cust_id": 11, "avail_balance": 9345.55 }, { "account_id": 29, "product_cd": "SBL", "cust_id": 13, "avail_balance": 50000 }]

exports.c9p2 = [{ "account_id": 25, "product_cd": "BUS", "cust_id": 10, "avail_balance": 0 }, { "account_id": 27, "product_cd": "BUS", "cust_id": 11, "avail_balance": 9345.55 }, { "account_id": 29, "product_cd": "SBL", "cust_id": 13, "avail_balance": 50000 }]

exports.c9p3 = [{ "emp_id": 1, "fname": "Michael", "lname": "Smith", "name": "mentor" }, { "emp_id": 2, "fname": "Susan", "lname": "Barker", "name": "worker" }, { "emp_id": 3, "fname": "Robert", "lname": "Tyler", "name": "mentor" }, { "emp_id": 4, "fname": "Susan", "lname": "Hawthorne", "name": "worker" }, { "emp_id": 5, "fname": "John", "lname": "Gooding", "name": "worker" }, { "emp_id": 6, "fname": "Helen", "lname": "Fleming", "name": "trainee" }, { "emp_id": 7, "fname": "Chris", "lname": "Tucker", "name": "trainee" }, { "emp_id": 8, "fname": "Sarah", "lname": "Parker", "name": "worker" }, { "emp_id": 9, "fname": "Jane", "lname": "Grossman", "name": "worker" }, { "emp_id": 10, "fname": "Paula", "lname": "Roberts", "name": "worker" }, { "emp_id": 11, "fname": "Thomas", "lname": "Ziegler", "name": "mentor" }, { "emp_id": 12, "fname": "Samantha", "lname": "Jameson", "name": "worker" }, { "emp_id": 13, "fname": "John", "lname": "Blake", "name": "mentor" }, { "emp_id": 14, "fname": "Cindy", "lname": "Mason", "name": "worker" }, { "emp_id": 15, "fname": "Frank", "lname": "Portman", "name": "worker" }, { "emp_id": 16, "fname": "Theresa", "lname": "Markham", "name": "mentor" }, { "emp_id": 17, "fname": "Beth", "lname": "Fowler", "name": "worker" }, { "emp_id": 18, "fname": "Rick", "lname": "Tulman", "name": "worker" }]

exports.c9p4 = [{ "emp_id": 1, "fname": "Michael", "lname": "Smith", "dept_name": "Administration", "branch_name": "Headquarters" }, { "emp_id": 2, "fname": "Susan", "lname": "Barker", "dept_name": "Administration", "branch_name": "Headquarters" }, { "emp_id": 3, "fname": "Robert", "lname": "Tyler", "dept_name": "Administration", "branch_name": "Headquarters" }, { "emp_id": 4, "fname": "Susan", "lname": "Hawthorne", "dept_name": "Operations", "branch_name": "Headquarters" }, { "emp_id": 5, "fname": "John", "lname": "Gooding", "dept_name": "Loans", "branch_name": "Headquarters" }, { "emp_id": 6, "fname": "Helen", "lname": "Fleming", "dept_name": "Operations", "branch_name": "Headquarters" }, { "emp_id": 7, "fname": "Chris", "lname": "Tucker", "dept_name": "Operations", "branch_name": "Headquarters" }, { "emp_id": 8, "fname": "Sarah", "lname": "Parker", "dept_name": "Operations", "branch_name": "Headquarters" }, { "emp_id": 9, "fname": "Jane", "lname": "Grossman", "dept_name": "Operations", "branch_name": "Headquarters" }, { "emp_id": 10, "fname": "Paula", "lname": "Roberts", "dept_name": "Operations", "branch_name": "Woburn Branch" }, { "emp_id": 11, "fname": "Thomas", "lname": "Ziegler", "dept_name": "Operations", "branch_name": "Woburn Branch" }, { "emp_id": 12, "fname": "Samantha", "lname": "Jameson", "dept_name": "Operations", "branch_name": "Woburn Branch" }, { "emp_id": 13, "fname": "John", "lname": "Blake", "dept_name": "Operations", "branch_name": "Quincy Branch" }, { "emp_id": 14, "fname": "Cindy", "lname": "Mason", "dept_name": "Operations", "branch_name": "Quincy Branch" }, { "emp_id": 15, "fname": "Frank", "lname": "Portman", "dept_name": "Operations", "branch_name": "Quincy Branch" }, { "emp_id": 16, "fname": "Theresa", "lname": "Markham", "dept_name": "Operations", "branch_name": "So. NH Branch" }, { "emp_id": 17, "fname": "Beth", "lname": "Fowler", "dept_name": "Operations", "branch_name": "So. NH Branch" }, { "emp_id": 18, "fname": "Rick", "lname": "Tulman", "dept_name": "Operations", "branch_name": "So. NH Branch" }]
